### ISSUE TITLE
TypeError: Cannot read property 'vehicleInfo' of undefined

### ISSUE THREAD

**Issue by larspetter** [joshperry/carwings#9]
Hi,

Trying to get it working here. Changed the region code and my login to username (old Leaf 2012) got it a step further :)

But it now stops giving me "TypeError: Cannot read property 'vehicleInfo' of undefined"

Running Node 8.3.0

The login seems to be successfull cause the app on my phone notices that a login has been done on another device.

Any ideas? The same login info/zone work the the pycarwings2-package so the login should be ok. Something else that is wrong.. :)

Full error:

TypeError: Cannot read property 'vehicleInfo' of undefined
at getsessionid (/usr/lib/node_modules/carwings/lib/index.js:72:33)
at p (/usr/lib/node_modules/carwings/lib/index.js:133:33)
at /usr/lib/node_modules/carwings/lib/index.js:85:12
at next (native)
at step (/usr/lib/node_modules/carwings/lib/index.js:42:191)
at /usr/lib/node_modules/carwings/lib/index.js:42:361
at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by larspetter** [comment]
Seems to be different responses around. To solve it with my EU 2012 modell I had to take away the VehicleInfoList-part of the response. Then it works fine.

function getsessionid(profile) {
  // return profile.VehicleInfoList.vehicleInfo[0].custom_sessionid;
  return profile.vehicleInfo[0].custom_sessionid;
}

function getvin(profile) {
  // return profile.VehicleInfoList.vehicleInfo[0].vin;
  return profile.vehicleInfo[0].vin;
}
